# Generated by Django 4.2 on 2023-04-05 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('photo', 'photo'), ('computer', 'computer')], max_length=100, null=True),
        ),
    ]
