# Generated by Django 4.2 on 2023-04-15 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_delete_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='index',
            field=models.CharField(choices=[('index', 'index'), ('products', 'products')], max_length=100, null=True),
        ),
    ]
