# Generated by Django 4.2 on 2023-04-15 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_remove_product_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='index',
            field=models.CharField(choices=[('index', 'index'), ('products', 'products')], max_length=100, null=True),
        ),
    ]
