# Generated by Django 4.2 on 2023-04-15 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_remove_product_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='index',
            field=models.CharField(choices=[('z', 'z'), ('p', 'p')], max_length=100, null=True),
        ),
    ]
