# Generated by Django 4.2 on 2023-04-15 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_remove_product_c_product_prrr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='prrr',
        ),
    ]
