# Generated by Django 4.2 on 2023-04-15 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_remove_product_prrr'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ra',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
