# Generated by Django 4.2 on 2023-04-15 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_product_ra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='ra',
        ),
    ]
