# Generated by Django 4.2 on 2023-04-15 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_alter_product_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cat',
            field=models.CharField(choices=[('i', 'i'), ('p', 'p')], default=1, max_length=90),
            preserve_default=False,
        ),
    ]
