# Generated by Django 4.2 on 2023-04-15 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_alter_product_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cat',
            field=models.TextField(choices=[('i', 'i'), ('p', 'p')]),
        ),
    ]
