# Generated by Django 4.2 on 2023-04-15 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_alter_product_cat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cat',
        ),
    ]
