# Generated by Django 4.2 on 2023-04-16 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0034_alter_product_cat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cat',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
